name: Check & Build Namadillo (with Input)

on:
#  schedule:
#    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:
    inputs:
      force_build:
        description: "Force the build, ignoring the last tag check"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      build_tag:
        description: 'A tag of the Namadillo source to use (otherwise latest is used)'
        default: ''
        required: false
        type: string

  push:
    tags:
      - "namadillo@*"

env:
  INDEXER_URL: https://namada-indexer.shield-crypto.com
  RPC_URL: https://namada-public-rpc.shield-crypto.com
  MASP_URL: https://namada-public-masp.shield-crypto.com
  CHAIN_ID: namada.5f5de2dd1b88cba30586420

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to check tags
          ssh-key: ${{ secrets.GH_PAT }}
      - name: Load last processed tag
        id: load-last-tag
        run: |
          if [[ -f .github/last_tag.txt ]]; then
            LAST_TAG=$(cat .github/last_tag.txt)
            echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
          else
            echo "LAST_TAG=" >> $GITHUB_ENV
          fi
          echo "Loaded Last Processed Tag. LAST_TAG=" 
      - name: Clone Namada repository
        uses: actions/checkout@v4
        with:
            repository: anoma/namada-interface
            fetch-depth: 0  # Fetch all history and tags
            path: source-repo
  
      - name: Fetch latest Namadillo tag
        id: check-tag
        run: |
          cd source-repo
          echo "Last Processed Tag. LAST_TAG=" 
          echo "LAST_TAG=" >> $GITHUB_ENV
          LATEST_TAG=$(git tag --sort=-creatordate | grep -E '^namadillo@' | head -n 1)
          echo "Latest tag from Namada: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

          USER_INPUT_TAG="${{ inputs.build_tag }}"
          if [[ -n "$USER_INPUT_TAG" ]]; then
            echo "LATEST_TAG=$USER_INPUT_TAG" >> "$GITHUB_ENV"
            echo "Using user input tag: $LATEST_TAG"
          fi

          FORCE_BUILD="${{ github.event.inputs.force_build || 'false' }}"
          echo "Force build: $FORCE_BUILD"

          if [[ "$LATEST_TAG" == "$LAST_TAG" && "$FORCE_BUILD" != "true" ]]; then
            echo "No new tag found. Exiting."
            exit 0
          fi
          echo "$LATEST_TAG" > ../.github/last_tag.txt
          echo "do_build=true" >> $GITHUB_ENV
          echo switching to $LATEST_TAG for the build process 
          git checkout $LATEST_TAG



      - name: Build and Release Namadillo
        uses: ./source-repo/.github/actions/release-project
        with:
          tag: $LATEST_TAG
          bundle_filename: $LATEST_TAG.zip
          working_dir: ./source-repo/apps/namadillo
